dist: bionic
language: java
#sudo: true

#matrix:
#  include:
#    - stage: build
#      script:
#    - script: source

addons:
  sonarcloud:
    organization: "slisnychyi" # the key of the org you chose at step #3
    token: "${SONAR_TOKEN}" # encrypted value of your token

install: source install.sh

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./mvnw clean install sonar:sonar -Dsonar.projectKey=sLisnychyi_travischeck; fi'
  - echo "hello i am here!"

after_script: source after.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'