dist: bionic
language: java
#sudo: true

#matrix:
#  include:
#    - stage: build
#      script:
#    - script: source

addons:
  sonarcloud:
    organization: "slisnychyi" # the key of the org you chose at step #3
    token: "${SONAR_TOKEN}" # encrypted value of your token

install: source install.sh

script:
